version: '3.2'
services:
  mendeleev:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.mendeleev
    environment:
      - POSTGRES_USER=mendeleev
      - POSTGRES_DB=mendeleev
      - POSTGRES_PASSWORD=goto@Experiment1
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=mendeleev
      - POSTGRES_DB=mendeleev
      - POSTGRES_PASSWORD=goto@Experiment1
    ports:
      - "5432:5432"
  rutherford:
    restart: always
    depends_on:
      - mendeleev
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.rutherford
    environment:
      - POSTGRES_USER=mendeleev
      - POSTGRES_DB=mendeleev
      - POSTGRES_PASSWORD=goto@Experiment1
    ports:
      - "8050:8050"