FROM python:3.7-slim

ENV APP_PATH=/usr/bin/app
RUN mkdir -p ${APP_PATH}
RUN mkdir -p ${APP_PATH}/data_input
WORKDIR ${APP_PATH}

ADD mendeleev-requirements.txt ${APP_PATH}/requirements.txt
RUN pip install -r requirements.txt
ADD /mendeleev ${APP_PATH}/mendeleev
ADD /tests ${APP_PATH}/tests

ENTRYPOINT ["python","mendeleev/main.py","/usr/bin/app/data_input"]
