version: '3.2'
services:
  mendeleev:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=mendeleev
      - POSTGRES_DB=mendeleev
      - POSTGRES_PASSWORD=goto@Experiment1
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=mendeleev
      - POSTGRES_DB=mendeleev
      - POSTGRES_PASSWORD=goto@Experiment1
    ports:
      - "5432:5432"


volumes:
  redis:
  superset: